version: '3.7'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    restart: "always"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env

  django_gunicorn:
    volumes:
      - static:/app/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: