# Generated by Django 4.1.3 on 2022-11-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tutorial_alter_about_id_alter_contact_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
