# Generated by Django 4.1.3 on 2022-11-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_tutorial_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "site_name_footer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "footer_caption",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
