# Generated by Django 4.1.3 on 2022-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_websitesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesetting",
            name="site_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="websitesetting",
            name="site_name_footer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
