# Generated by Django 4.1.3 on 2022-11-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_websitesetting_site_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Topic",
            new_name="Tag",
        ),
        migrations.AlterModelOptions(
            name="tutorial",
            options={"ordering": ["-updated_at", "-created_at", "name"]},
        ),
        migrations.RemoveField(
            model_name="post",
            name="topic",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="blog.tag"),
        ),
        migrations.AlterField(
            model_name="info",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="info/"),
        ),
        migrations.AlterField(
            model_name="info",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resume/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="tutorial/"),
        ),
    ]
