# Generated by Django 4.1.3 on 2022-11-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_topic_tag_alter_tutorial_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
            ],
        ),
    ]
