# Generated by Django 4.1.3 on 2022-11-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_ipmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-updated_at", "title"]},
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="views",
        ),
        migrations.RemoveField(
            model_name="post",
            name="views",
        ),
        migrations.AddField(
            model_name="lesson",
            name="views",
            field=models.ManyToManyField(to="blog.ipmodel"),
        ),
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.ManyToManyField(to="blog.ipmodel"),
        ),
    ]
