# Generated by Django 4.1.3 on 2022-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_lesson_views_alter_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="views",
            field=models.ManyToManyField(blank=True, to="blog.ipmodel"),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.ManyToManyField(blank=True, to="blog.ipmodel"),
        ),
    ]
